In [3]:
"""tic tac toe a gamed played with X and O
in this game the playe wins if either there are three X or O connected either horizontal, vertical or diagonal as the
symbol chosen by the player
usuallyed played with a 3x3 matrix"""

import numpy as np
import random
from time import sleep

def player_board(): #creates a blank board for the game
    return np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]])

def game(chart): #checks if the board is empty or not
    t=[]
    for i in range(len(chart)):
        for j in range(len(chart)):
            if chart[i][j]==0:
                t.append((i,j))
    return(t)

# Select a random place for the player 
def random_place(chart, player): 
    select = game(chart) 
    cur_loc = random.choice(select) 
    chart[cur_loc] = player 
    return(chart) 


def r_win(chart,player): #checks if the player has three marks toghther horizontally(row)
    for x in range(len(chart)): 
        win = True
          
        for y in range(len(chart)): 
            if chart[x, y] != player: 
                win = False
                continue
                  
        if win == True: 
            return(win) 
    return(win) 

def c_win(chart, player): #checks whether the player has three marks toghter vertically(columns)
    for x in range(len(chart)): 
        win = True
          
        for y in range(len(chart)): 
            if chart[y][x] != player: 
                win = False
                continue
                  
        if win == True: 
            return(win) 
    return(win)

def diag_win(chart, player): #checks if the player has three symbols diagonally
    win = True
    y = 0
    for x in range(len(chart)): 
        if chart[x, x] != player: 
            win = False
    if win: 
        return win 
    win = True
    if win: 
        for x in range(len(chart)): 
            y = len(chart) - 1 - x 
            if chart[x, y] != player: 
                win = False
    return win 
  
def evaluate(chart): #checks if it is a tie or there is a winner  
    winner = 0
      
    for player in [1, 2]: 
        if (r_win(chart, player) or
            c_win(chart,player) or 
            diag_win(chart,player)): 
                 
            winner = player 
              
    if np.all(chart != 0) and winner == 0: 
        winner = -1
    return winner 
  
# Main function to start the game 
def play_game(): 
    chart, winner, counter = player_board(), 0, 1
    print(chart) 
    sleep(2) 
      
    while winner == 0: 
        for player in [1, 2]: 
            chart = random_place(chart, player) 
            print("Board after " + str(counter) + " move") 
            print(chart) 
            sleep(2) 
            counter += 1
            winner = evaluate(chart) 
            if winner != 0: 
                break
    return(winner) 
  
# Driver Code 
print("Winner is: " + str(play_game())) 

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 1]
 [0 0 0]
 [0 0 0]]
Board after 2 move
[[0 0 1]
 [0 0 0]
 [0 2 0]]
Board after 3 move
[[0 0 1]
 [0 0 1]
 [0 2 0]]
Board after 4 move
[[2 0 1]
 [0 0 1]
 [0 2 0]]
Board after 5 move
[[2 0 1]
 [0 0 1]
 [0 2 1]]
Winner is: 1
